-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 00:42:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project'
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project'
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project'` DEFAULT CHARACTER SET utf8 ;
USE `project'` ;

-- -----------------------------------------------------
-- Table `project'`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`Branch` (
  `Branch_ID` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(15) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Branch_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`employess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`employess` (
  `employess_ID` INT NOT NULL,
  `first_name` VARCHAR(10) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `job_title` VARCHAR(45) NOT NULL,
  `birth_day` DATE NOT NULL,
  `hire_date` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NOT NULL,
  `extenstion` VARCHAR(45) NOT NULL,
  `photo` BLOB NULL,
  `salary` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `reports_to` INT NOT NULL,
  `branch_ID` INT NOT NULL,
  PRIMARY KEY (`employess_ID`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `branch_ID_idx` (`branch_ID` ASC) VISIBLE,
  INDEX `employess_ID_idx` (`reports_to` ASC) VISIBLE,
  CONSTRAINT `branch_ID`
    FOREIGN KEY (`branch_ID`)
    REFERENCES `project'`.`Branch` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employess_ID`
    FOREIGN KEY (`reports_to`)
    REFERENCES `project'`.`employess` (`employess_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`salaries` (
  `employee_id` INT NOT NULL,
  `salary` INT NOT NULL,
  `taxes` INT NOT NULL,
  `days_diducte` INT NULL DEFAULT 0,
  `benefits` VARCHAR(45) NULL,
  `from_date` DATE NOT NULL,
  `to_date` DATE NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project'`.`employess` (`employess_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`shippers` (
  `shipper_id` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`shipper_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`invoices` (
  `invoice_id` INT NOT NULL,
  `order_number` VARCHAR(45) NOT NULL,
  `item_id` VARCHAR(45) NOT NULL,
  `item_cost` VARCHAR(45) NOT NULL,
  `discount` VARCHAR(45) NULL,
  `invoice_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`invoice_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`customer` (
  `customerNumber` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `national_id` VARCHAR(15) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `customercol` ENUM('Male', 'Female') NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`customerNumber`),
  UNIQUE INDEX `national_id_UNIQUE` (`national_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`orders` (
  `order_number` INT NOT NULL,
  `orderdate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NOT NULL,
  `ship_id` INT NOT NULL,
  `freight` VARCHAR(45) NOT NULL,
  `ship_name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(45) NULL,
  `CustomerNumber` INT NOT NULL,
  `Payment_type'` INT NOT NULL,
  `empolyee_id` INT NOT NULL,
  PRIMARY KEY (`order_number`),
  INDEX `employee_id_idx` (`empolyee_id` ASC) VISIBLE,
  INDEX `con_shipper_id_idx` (`ship_id` ASC) VISIBLE,
  INDEX `con_invoice_id_idx` (`Payment_type'` ASC) VISIBLE,
  INDEX `con_customer_id_idx` (`CustomerNumber` ASC) VISIBLE,
  CONSTRAINT `con_employee_id`
    FOREIGN KEY (`empolyee_id`)
    REFERENCES `project'`.`employess` (`employess_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_shipper_id`
    FOREIGN KEY (`ship_id`)
    REFERENCES `project'`.`shippers` (`shipper_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_invoice_id`
    FOREIGN KEY (`Payment_type'`)
    REFERENCES `project'`.`invoices` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_customer_number`
    FOREIGN KEY (`CustomerNumber`)
    REFERENCES `project'`.`customer` (`customerNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`payment_method` (
  `payment_id` INT NOT NULL,
  `payment_type` ENUM('cash', 'on account') NOT NULL,
  `customer_number` INT NOT NULL,
  `payment_total` INT NOT NULL,
  INDEX `payment_id_cons_idx` (`customer_number` ASC) VISIBLE,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `customer_id_cons`
    FOREIGN KEY (`customer_number`)
    REFERENCES `project'`.`customer` (`customerNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`suppliers` (
  `suppliers_id` INT NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `homePage` VARCHAR(45) NULL,
  PRIMARY KEY (`suppliers_id`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `descreption` VARCHAR(45) NOT NULL,
  `picture` BLOB NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`product` (
  `product_id` INT NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  `productLine` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `quantity_per_unit` INT NOT NULL,
  `unit_price` INT NOT NULL,
  `units_in_stock` INT NOT NULL,
  `units_on_order` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `supplier_id_cons_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `category_id_cons_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id_cons`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `project'`.`suppliers` (`suppliers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id_cons`
    FOREIGN KEY (`category_id`)
    REFERENCES `project'`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project'`.`orderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project'`.`orderDetails` (
  `order_number` INT NOT NULL,
  `product_id` INT NOT NULL,
  `QuantityOrdered` INT NOT NULL,
  `priceEach` INT NOT NULL,
  `discount` INT NOT NULL,
  INDEX `order_id_cons_idx` (`order_number` ASC) VISIBLE,
  INDEX `product_id_cons_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_id_cons`
    FOREIGN KEY (`order_number`)
    REFERENCES `project'`.`orders` (`order_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id_cons`
    FOREIGN KEY (`product_id`)
    REFERENCES `project'`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
